### ISSUE TITLE
setup-antlr4 does not use node16

### ISSUE THREAD

**Issue by troisdiz** [StoneMoe/setup-antlr4#2]
When using the action, the following message is displayed:

The following actions uses node12 which is deprecated and will be forced to run on node16: StoneMoe/setup-antlr4@v2, actions/upload-artifact@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by StoneMoe** [comment]
It's now released, thanks.
